azs:
- name: z1
  cloud_properties: {availability_zone: us-east-1a}
- name: z2
  cloud_properties: {availability_zone: us-east-1b}

vm_types:
- name: small
  cloud_properties:
    instance_type: t2.micro
    ephemeral_disk: {size: 3000, type: gp2}
- name: medium
  cloud_properties:
    instance_type: m3.medium
    ephemeral_disk: {size: 30000, type: gp2}

vm_extensions:
- name: concourse-lbs
  cloud_properties:
    elbs: [sding-bosh-Concourse-Elb]
- name: worker-ephemeral
  cloud_properties:
    ephemeral_disk:
      size: 60_000
      type: gp2
disk_types:
- name: small
  disk_size: 3000
  cloud_properties: {type: gp2}
- name: large
  disk_size: 50_000
  cloud_properties: {type: gp2}

networks:
- name: private
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    az: z1
    static: [10.0.1.30]
    dns: [10.0.0.2]
    reserved: [10.0.1.2 - 10.0.1.20]
    cloud_properties: {subnet: {{my_subnet}}}
- name: cf1
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    az: z1
    static:
    - 10.0.1.21 - 10.0.1.30
    dns: [10.0.0.2]
    reserved:
    - 10.0.1.2 - 10.0.1.20
    - 10.0.1.130 - 10.0.1.254
    cloud_properties: {subnet: {{subnet_az1}}}
- name: cf2
  type: manual
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    az: z2
    static:
    - 10.0.2.21 - 10.0.2.30
    dns: [10.0.0.2]
    reserved:
    - 10.0.2.2 - 10.0.2.20
    - 10.0.2.130 - 10.0.2.254
    cloud_properties: {subnet: {{subnet_az2}}}
- name: diego1
  type: manual
  subnets:
  - range: 10.0.1.0/24
    gateway: 10.0.1.1
    az: z1
    static:
    - 10.0.1.131 - 10.0.1.140
    dns: [10.0.0.2]
    reserved:
    - 10.0.1.2 - 10.0.1.130
    cloud_properties: {subnet: {{subnet_az1}}}
- name: diego2
  type: manual
  subnets:
  - range: 10.0.2.0/24
    gateway: 10.0.2.1
    az: z2
    static:
    - 10.0.2.131 - 10.0.2.140
    dns: [10.0.0.2]
    reserved:
    - 10.0.2.2 - 10.0.2.130
    cloud_properties: {subnet: {{subnet_az2}}}
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: medium
  network: private
